name: Build & Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        vscodeVersion:
          # - 1.64.2
          - stable
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
      - name: Install NPM Packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Install webview-ui NPM Packages
        run: npm ci
        working-directory: ./webview-ui
      - name: Lint webview-ui
        run: npm run lint
        working-directory: ./webview-ui
      - name: Build webview-ui
        run: npm run build
        working-directory: ./webview-ui
      - name: Package extension
        run: npm run package
      - name: Prepare test project
        run: |
          dotnet tool restore
          dotnet build
          dotnet ef --version
        working-directory: ./sample_dotnet

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Install webview-ui NPM Packages
        run: npm ci
        working-directory: ./webview-ui
      - name: Build webview-ui
        run: npm run build
        working-directory: ./webview-ui
      - name: Build & publish extension
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          npm run publish -- -p "$AZURE_TOKEN"
