name: Build & Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install NPM Packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run package

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install packages
        run: npm ci
      - name: Build & publish extension
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
          VSX_REGISTRY_ACCESS_TOKEN: ${{ secrets.VSX_REGISTRY_ACCESS_TOKEN }}
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          npm run publish -- -p "$AZURE_TOKEN"
